sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install tox

script:
  - tox

# notifications:
#   email: false